@baseUrl=http://localhost:8888/api/v1

### User Registration
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "verify_key": "buihuyphuc97@gmail.com",
  "verify_type": 1,
  "verify_purpose": "TEST_USER"
}
