// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 00004_pre_go_acc_user_two_factor_9999.sql

package database

import (
	"context"
	"database/sql"
)

const addOrUpdateEmail = `-- name: AddOrUpdateEmail :exec
INSERT INTO ` + "`" + `pre_go_acc_user_two_factor_9999` + "`" + ` (user_id, two_factor_email, two_factor_is_active)
VALUES (?, ?, b'1')
ON DUPLICATE KEY UPDATE two_factor_email = ?, two_factor_updated_at = now()
`

type AddOrUpdateEmailParams struct {
	UserID           int32
	TwoFactorEmail   sql.NullString
	TwoFactorEmail_2 sql.NullString
}

func (q *Queries) AddOrUpdateEmail(ctx context.Context, arg AddOrUpdateEmailParams) error {
	_, err := q.db.ExecContext(ctx, addOrUpdateEmail, arg.UserID, arg.TwoFactorEmail, arg.TwoFactorEmail_2)
	return err
}

const addOrUpdatePhone = `-- name: AddOrUpdatePhone :exec
INSERT INTO ` + "`" + `pre_go_acc_user_two_factor_9999` + "`" + ` (user_id, two_factor_phone, two_factor_is_active)
VALUES (?, ?, b'1')
ON DUPLICATE KEY UPDATE two_factor_phone = ?, two_factor_updated_at = now()
`

type AddOrUpdatePhoneParams struct {
	UserID           int32
	TwoFactorPhone   sql.NullString
	TwoFactorPhone_2 sql.NullString
}

func (q *Queries) AddOrUpdatePhone(ctx context.Context, arg AddOrUpdatePhoneParams) error {
	_, err := q.db.ExecContext(ctx, addOrUpdatePhone, arg.UserID, arg.TwoFactorPhone, arg.TwoFactorPhone_2)
	return err
}

const countActiveTwoFactorMethods = `-- name: CountActiveTwoFactorMethods :one
SELECT COUNT(*)
FROM ` + "`" + `pre_go_acc_user_two_factor_9999` + "`" + `
WHERE user_id = ? AND two_factor_is_active = b'1'
`

func (q *Queries) CountActiveTwoFactorMethods(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveTwoFactorMethods, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const disableTwoFactor = `-- name: DisableTwoFactor :exec
UPDATE ` + "`" + `pre_go_acc_user_two_factor_9999` + "`" + `
SET two_factor_is_active = 0,
    two_factor_updated_at = now()
WHERE user_id = ? AND two_factor_auth_type = ?
`

type DisableTwoFactorParams struct {
	UserID            int32
	TwoFactorAuthType uint8
}

func (q *Queries) DisableTwoFactor(ctx context.Context, arg DisableTwoFactorParams) error {
	_, err := q.db.ExecContext(ctx, disableTwoFactor, arg.UserID, arg.TwoFactorAuthType)
	return err
}

const enableTwoFactorTypeEmail = `-- name: EnableTwoFactorTypeEmail :exec
INSERT INTO ` + "`" + `pre_go_acc_user_two_factor_9999` + "`" + ` (user_id, two_factor_auth_type, two_factor_email, two_factor_auth_secret, two_factor_is_active, two_factor_created_at, two_factor_updated_at)
VALUES (?, ?, ?, "OTP", 0, now(), now())
`

type EnableTwoFactorTypeEmailParams struct {
	UserID            int32
	TwoFactorAuthType uint8
	TwoFactorEmail    sql.NullString
}

func (q *Queries) EnableTwoFactorTypeEmail(ctx context.Context, arg EnableTwoFactorTypeEmailParams) error {
	_, err := q.db.ExecContext(ctx, enableTwoFactorTypeEmail, arg.UserID, arg.TwoFactorAuthType, arg.TwoFactorEmail)
	return err
}

const getTwoFactorMethodByID = `-- name: GetTwoFactorMethodByID :one
SELECT two_factor_id, user_id, two_factor_auth_type, two_factor_auth_secret, two_factor_phone, two_factor_email, two_factor_is_active, two_factor_created_at, two_factor_updated_at
FROM ` + "`" + `pre_go_acc_user_two_factor_9999` + "`" + `
WHERE user_id = ?
`

func (q *Queries) GetTwoFactorMethodByID(ctx context.Context, userID int32) (PreGoAccUserTwoFactor9999, error) {
	row := q.db.QueryRowContext(ctx, getTwoFactorMethodByID, userID)
	var i PreGoAccUserTwoFactor9999
	err := row.Scan(
		&i.TwoFactorID,
		&i.UserID,
		&i.TwoFactorAuthType,
		&i.TwoFactorAuthSecret,
		&i.TwoFactorPhone,
		&i.TwoFactorEmail,
		&i.TwoFactorIsActive,
		&i.TwoFactorCreatedAt,
		&i.TwoFactorUpdatedAt,
	)
	return i, err
}

const getTwoFactorMethodByIDAndType = `-- name: GetTwoFactorMethodByIDAndType :one
SELECT two_factor_id, user_id, two_factor_auth_type, two_factor_auth_secret, two_factor_phone, two_factor_email, two_factor_is_active, two_factor_created_at, two_factor_updated_at
FROM ` + "`" + `pre_go_acc_user_two_factor_9999` + "`" + `
WHERE user_id = ? AND two_factor_auth_type = ?
`

type GetTwoFactorMethodByIDAndTypeParams struct {
	UserID            int32
	TwoFactorAuthType uint8
}

func (q *Queries) GetTwoFactorMethodByIDAndType(ctx context.Context, arg GetTwoFactorMethodByIDAndTypeParams) (PreGoAccUserTwoFactor9999, error) {
	row := q.db.QueryRowContext(ctx, getTwoFactorMethodByIDAndType, arg.UserID, arg.TwoFactorAuthType)
	var i PreGoAccUserTwoFactor9999
	err := row.Scan(
		&i.TwoFactorID,
		&i.UserID,
		&i.TwoFactorAuthType,
		&i.TwoFactorAuthSecret,
		&i.TwoFactorPhone,
		&i.TwoFactorEmail,
		&i.TwoFactorIsActive,
		&i.TwoFactorCreatedAt,
		&i.TwoFactorUpdatedAt,
	)
	return i, err
}

const getTwoFactorMethods = `-- name: GetTwoFactorMethods :many
SELECT two_factor_id, user_id, two_factor_auth_type, two_factor_auth_secret, two_factor_phone, two_factor_email, two_factor_is_active, two_factor_created_at, two_factor_updated_at
FROM ` + "`" + `pre_go_acc_user_two_factor_9999` + "`" + `
WHERE user_id = ?
`

func (q *Queries) GetTwoFactorMethods(ctx context.Context, userID int32) ([]PreGoAccUserTwoFactor9999, error) {
	rows, err := q.db.QueryContext(ctx, getTwoFactorMethods, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreGoAccUserTwoFactor9999
	for rows.Next() {
		var i PreGoAccUserTwoFactor9999
		if err := rows.Scan(
			&i.TwoFactorID,
			&i.UserID,
			&i.TwoFactorAuthType,
			&i.TwoFactorAuthSecret,
			&i.TwoFactorPhone,
			&i.TwoFactorEmail,
			&i.TwoFactorIsActive,
			&i.TwoFactorCreatedAt,
			&i.TwoFactorUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTwoFactorStatus = `-- name: GetTwoFactorStatus :one
SELECT two_factor_is_active
FROM ` + "`" + `pre_go_acc_user_two_factor_9999` + "`" + `
WHERE user_id = ? AND two_factor_auth_type = ?
`

type GetTwoFactorStatusParams struct {
	UserID            int32
	TwoFactorAuthType uint8
}

func (q *Queries) GetTwoFactorStatus(ctx context.Context, arg GetTwoFactorStatusParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTwoFactorStatus, arg.UserID, arg.TwoFactorAuthType)
	var two_factor_is_active interface{}
	err := row.Scan(&two_factor_is_active)
	return two_factor_is_active, err
}

const isTwoFactorEnabled = `-- name: IsTwoFactorEnabled :one
SELECT COUNT(*)
FROM ` + "`" + `pre_go_acc_user_two_factor_9999` + "`" + `
WHERE user_id = ? AND two_factor_is_active = b'1'
`

func (q *Queries) IsTwoFactorEnabled(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, isTwoFactorEnabled, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const reactivateTwoFactor = `-- name: ReactivateTwoFactor :exec
UPDATE ` + "`" + `pre_go_acc_user_two_factor_9999` + "`" + `
SET two_factor_is_active = b'1',
    two_factor_updated_at = now()
WHERE user_id = ? AND two_factor_auth_type = ?
`

type ReactivateTwoFactorParams struct {
	UserID            int32
	TwoFactorAuthType uint8
}

func (q *Queries) ReactivateTwoFactor(ctx context.Context, arg ReactivateTwoFactorParams) error {
	_, err := q.db.ExecContext(ctx, reactivateTwoFactor, arg.UserID, arg.TwoFactorAuthType)
	return err
}

const removeTwoFactor = `-- name: RemoveTwoFactor :exec
DELETE FROM ` + "`" + `pre_go_acc_user_two_factor_9999` + "`" + `
WHERE user_id = ? AND two_factor_auth_type = ?
`

type RemoveTwoFactorParams struct {
	UserID            int32
	TwoFactorAuthType uint8
}

func (q *Queries) RemoveTwoFactor(ctx context.Context, arg RemoveTwoFactorParams) error {
	_, err := q.db.ExecContext(ctx, removeTwoFactor, arg.UserID, arg.TwoFactorAuthType)
	return err
}

const updateTwoFactorStatus = `-- name: UpdateTwoFactorStatus :exec
UPDATE ` + "`" + `pre_go_acc_user_two_factor_9999` + "`" + `
SET two_factor_is_active = b'1',
    two_factor_updated_at = now()
WHERE user_id = ? AND two_factor_auth_type = ? AND two_factor_is_active = b'0'
`

type UpdateTwoFactorStatusParams struct {
	UserID            int32
	TwoFactorAuthType uint8
}

func (q *Queries) UpdateTwoFactorStatus(ctx context.Context, arg UpdateTwoFactorStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTwoFactorStatus, arg.UserID, arg.TwoFactorAuthType)
	return err
}

const verifyTwoFactor = `-- name: VerifyTwoFactor :one
SELECT COUNT(*)
FROM ` + "`" + `pre_go_acc_user_two_factor_9999` + "`" + `
WHERE user_id = ? AND two_factor_auth_type = ? AND two_factor_is_active = b'1'
`

type VerifyTwoFactorParams struct {
	UserID            int32
	TwoFactorAuthType uint8
}

func (q *Queries) VerifyTwoFactor(ctx context.Context, arg VerifyTwoFactorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, verifyTwoFactor, arg.UserID, arg.TwoFactorAuthType)
	var count int64
	err := row.Scan(&count)
	return count, err
}
