FROM golang:alpine

WORKDIR /app

# Cài git + air
RUN apk add --no-cache git
RUN go install github.com/air-verse/air@latest

# Copy go mod trước để cache
COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8888

CMD [ "air", "-c", ".air.dev.toml", "-d" ]
