basePath: /api/v1
definitions:
  dto.LoginRequest:
    properties:
      user_account:
        type: string
      user_password:
        type: string
    type: object
  dto.RegisterRequest:
    properties:
      verify_key:
        type: string
      verify_purpose:
        type: string
      verify_type:
        type: integer
    type: object
  dto.SetupTwoFactorAuthRequest:
    properties:
      two_factor_auth_type:
        type: string
      two_factor_email:
        type: string
      user_id:
        type: integer
    type: object
  dto.UpdatePasswordRegisterRequest:
    properties:
      password:
        type: string
      token:
        type: string
    type: object
  dto.VerifyOTPRequest:
    properties:
      verify_code:
        type: string
      verify_key:
        type: string
    type: object
  dto.VerifyTwoFactorAuthRequest:
    properties:
      two_factor_code:
        type: string
      user_id:
        type: integer
    type: object
  response.ErrorResponseData:
    properties:
      detail: {}
      error:
        type: string
      internal_code:
        type: integer
    type: object
  response.ResponseData:
    properties:
      data: {}
      internal_code:
        type: integer
      message:
        type: string
    type: object
host: localhost:8888
info:
  contact:
    email: buihuyphuc97@gmail.com
    name: TEAM PHUCBUI
    url: https://github.com/BuiHuyPhuc/go-learning
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/BuiHuyPhuc/go-learning
  title: API Documentation Ecommerce Backend SHOPDEVGO
  version: 1.0.0
paths:
  /users/login:
    post:
      consumes:
      - application/json
      description: User Login
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      summary: User Login
      tags:
      - account management
  /users/register:
    post:
      consumes:
      - application/json
      description: When user is registerd send otp  to email
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      summary: User Registration
      tags:
      - account management
  /users/two-factor/setup:
    post:
      consumes:
      - application/json
      description: User Setup Two Factor Authentication
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.SetupTwoFactorAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      summary: User Setup Two Factor Authentication
      tags:
      - account 2fa
  /users/two-factor/verify:
    post:
      consumes:
      - application/json
      description: User Verify Two Factor Authentication
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.VerifyTwoFactorAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      summary: User Verify Two Factor Authentication
      tags:
      - account 2fa
  /users/update-pass-register:
    post:
      consumes:
      - application/json
      description: When user is registerd send otp  to email
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.UpdatePasswordRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      summary: Update Password Register
      tags:
      - account management
  /users/verify-account:
    post:
      consumes:
      - application/json
      description: When user is registerd send otp  to email
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.VerifyOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      summary: Verify OTP Login By User
      tags:
      - account management
schemes:
- http
swagger: "2.0"
