server:
  port: 8888
  mode: dev
logger:
  level: debug
  path: ./storages/logs/dev.001.log
  maxSize: 500  # megabytes
  maxBackups: 3
  maxAge: 28
  compress: true # disabled by default
mysql:
  host: 127.0.0.1       # 127.0.0.1 - mysql
  port: 33306           # 33306     - 3306
  username: root
  password: root123
  dbname: shopdevgo
  maxIdleConns: 10      #  conn pool tối đa
  maxOpenConns: 100     #  conn tối đa của máy chủ vật lý
  connMaxIdleTime: 300  #  thời gian tối đa rảnh của 1 conn
  connMaxLifetime: 300  #  vòng đời tối đa của 1 conn
redis:
  host: 127.0.0.1       # 127.0.0.1 - redis
  port: 6381            # 6381      - 6379
  password:
  db: 0
